Configure github actions to deploy to CF pages

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -16,7 +16,7 @@ permissions:
   checks: write
 
 jobs:
-  linting:
+  lint:
     name: Lint files
     runs-on: ubuntu-latest
     steps:
@@ -38,7 +38,7 @@ jobs:
       - name: Lint
         run: pnpm lint
 
-  tests:
+  test:
     name: Run tests
     runs-on: ubuntu-latest
     steps:
@@ -60,7 +60,7 @@ jobs:
       - name: Test code
         run: pnpm test:cov
 
-      - name: Check if CODECOV_TOKEN exists
+      - name: Check if can publish code coverage
         id: check_codecov
         run: |
           if [ "$CODECOV_TOKEN" == "" ]; then
@@ -77,9 +77,17 @@ jobs:
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
 
-  build:
-    name: Build packages
+  publish:
+    name: Publish to CF pages
     runs-on: ubuntu-latest
+    needs:
+      - lint
+      - test
+    environment:
+      name: Staging
+      url: ${{ steps.publish-client.outputs.url }}
+    outputs:
+      url: ${{ steps.publish-client.outputs.url }}
     steps:
       - name: Checkout git repository
         uses: actions/checkout@v3
@@ -98,3 +106,47 @@ jobs:
 
       - name: Build
         run: pnpm build
+
+      - name: Check if can publish to cloudflare
+        id: check_cf_pages
+        run: |
+          if [ "$CLOUDFLARE_API_TOKEN" == "" ] \
+          || [ "$CLOUDFLARE_ACCOUNT_ID" == "" ]; then
+            echo "publish_cf_pages=0" >> $GITHUB_OUTPUT
+          else
+            echo "publish_cf_pages=1" >> $GITHUB_OUTPUT
+          fi
+        env:
+          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
+          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
+
+      - name: Publish client to cloudflare
+        if: (steps.check_cf_pages.outputs.publish_cf_pages == '1')
+        id: publish-client
+        working-directory: apps/client/
+        run: |
+          if [[ "${{ github.ref }}" =~ refs/pull/.+ ]]; then
+            # Pull requests deploy to their own staging environments
+            : "${{ github.ref }}"
+            : ${_%%\/merge}  # Remove 'merge' at the end
+            : ${_//refs\/pull\/}  # Remove 'refs' at the beginning
+            TARGET="PR-${_}"
+          else
+            TARGET="${{ github.ref_name }}"
+          fi
+
+          # Use wrangler to manually deploy to cloudflare
+          pnpm dlx wrangler pages publish www/ --project-name=crafts-staging \
+            --branch="$TARGET" --commit-dirty=true | tee wrangler.out
+
+          # Parse the output URL from the wrangler output
+          TARGET_URL=$(grep -oE "https?://.+" wrangler.out | tail -n1)
+          if [[ "$TARGET_URL" ]]; then
+            echo "::set-output name=url::$TARGET_URL"
+          else
+            echo "Failed to find URL for deployment"
+            exit 1
+          fi
+        env:
+          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
+          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
